INSERT INTO "Staff" ("id", "region", "name", "startTime", "carPlate") VALUES 
(lower(hex(randomblob(16))), 'ภาคเหนือ', '(ภาคเหนือ) วันจันทร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคเหนือ', '(ภาคเหนือ) วันอังคาร', '', ''),
(lower(hex(randomblob(16))), 'ภาคเหนือ', '(ภาคเหนือ) วันพุธ', '', ''),
(lower(hex(randomblob(16))), 'ภาคเหนือ', '(ภาคเหนือ) วันพฤหัสบดี', '', ''),
(lower(hex(randomblob(16))), 'ภาคเหนือ', '(ภาคเหนือ) วันศุกร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคเหนือ', '(ภาคเหนือ) วันเสาร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคเหนือ', '(ภาคเหนือ) วันอาทิตย์', '', ''),
(lower(hex(randomblob(16))), 'ภาคอีสาน', '(ภาคอีสาน) วันจันทร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคอีสาน', '(ภาคอีสาน) วันอังคาร', '', ''),
(lower(hex(randomblob(16))), 'ภาคอีสาน', '(ภาคอีสาน) วันพุธ', '', ''),
(lower(hex(randomblob(16))), 'ภาคอีสาน', '(ภาคอีสาน) วันพฤหัสบดี', '', ''),
(lower(hex(randomblob(16))), 'ภาคอีสาน', '(ภาคอีสาน) วันศุกร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคอีสาน', '(ภาคอีสาน) วันเสาร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคอีสาน', '(ภาคอีสาน) วันอาทิตย์', '', ''),
(lower(hex(randomblob(16))), 'ภาคใต้', '(ภาคใต้) วันจันทร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคใต้', '(ภาคใต้) วันอังคาร', '', ''),
(lower(hex(randomblob(16))), 'ภาคใต้', '(ภาคใต้) วันพุธ', '', ''),
(lower(hex(randomblob(16))), 'ภาคใต้', '(ภาคใต้) วันพฤหัสบดี', '', ''),
(lower(hex(randomblob(16))), 'ภาคใต้', '(ภาคใต้) วันศุกร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคใต้', '(ภาคใต้) วันเสาร์', '', ''),
(lower(hex(randomblob(16))), 'ภาคใต้', '(ภาคใต้) วันอาทิตย์', '', '')
ON CONFLICT(name) DO NOTHING;
